myCrudproject/crudprojectapp/urls.py
from django.urls import path
from .views import HomePage, Register, Login, addnew, edit, update, destroy, logoutuser, landinpage


urlpatterns = [
    path('', landinpage, name="land-page"),
    path('home/', HomePage, name="home-page"),
    path('register/', Register, name="register-page"),
    path('login/', Login, name="login-page"),
    path('addnew', addnew, name='addnew'),  
    path('edit/<int:id>', edit, name='edit'),  
    path('update/<int:id>', update, name='update'),  
    path('delete/<int:id>', destroy, name='destroy'), 
    path('logout/', logoutuser, name='logout'),
]

myCrudproject/myCrudproject/urls.py
from django.contrib import admin
from django.urls import path, include
from crudprojectapp import views  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudprojectapp.urls')),
   
     
]

myCrudproject/crudprojectapp/models.py
from django.db import models

# Create your models here.
class Student(models.Model):  
    fname = models.CharField(max_length=100)  
    lname = models.CharField(max_length=100)
    gender = models.CharField(max_length=10, choices=[("Female", "Female"), ("Male", "Male"), ("Other", "Other")], default=None )
    address = models.CharField(max_length=100)
    email = models.EmailField()  
    contact = models.PositiveIntegerField() 
   
    class Meta:  
        db_table = "tblstudent"

myCrudproject/crudprojectapp/forms.py
from django import forms  
from crudprojectapp.models import Student  

class StudentForm(forms.ModelForm):  
 
    # gender = forms.ChoiceField(
    #         choices=[("Female", "Female"), ("Male", "Male"), ("Other", "Other")],
    #         widget=forms.RadioSelect(attrs={'class': 'radio-inline'}),
    #     )


    class Meta:  
        model = Student  
        fields = ['fname','lname','gender', 'address','email','contact'] 
      
        widgets = { 
            'fname': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'lname': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'gender': forms.RadioSelect(attrs={'class': 'radio-inline'}),
            'address': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'email': forms.EmailInput(attrs={ 'class': 'form-control' }),
            'contact': forms.NumberInput(attrs={ 'class': 'form-control' }),
      }
        
        

myCrudproject/crudprojectapp/views.py
from django.shortcuts import render, redirect  
from crudprojectapp.forms import StudentForm  
from crudprojectapp.models import Student  
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.  


def landinpage(request):
     return render(request, 'register.html', {})

@login_required 
def HomePage(request):  
    student = Student.objects.all()  
    return render(request,"show.html",{'student':student})  


def Register(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        name = request.POST.get('uname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        new_user = User.objects.create_user(name, email, password)
        new_user.first_name = fname
        new_user.last_name = lname

        new_user.save()
        return redirect('home-page')
    
    return render(request, 'register.html', {})


def Login(request):
    if request.method == 'POST':
        name = request.POST.get('uname')
        password = request.POST.get('password')

        user = authenticate(request, username=name, password=password)
        if user is not None:
            login(request, user)
            return redirect('home-page')
        else:
            return render(request, 'register.html', {'error_message': 'Invalid credentials'})

    return render(request, 'register.html', {})

def logoutuser(request):
    logout(request)
    return redirect('/')


#  add function
def addnew(request):  
    if request.method == "POST":  
        form = StudentForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('home-page')  
            except:  
                pass
    else:  
        form = StudentForm()  
    return render(request,'index.html',{'form':form})  
 

# Edit function
def edit(request, id):  
    student = Student.objects.get(id=id)  
    return render(request,'edit.html', {'student':student})  

# update function 
def update(request, id):  
    student = Student.objects.get(id=id)  
    form = StudentForm(request.POST, instance = student)  
    if form.is_valid():  
        form.save()  
        return redirect("home-page")  
    return render(request, 'edit.html', {'student': student})  
     
def destroy(request, id):  
    student = Student.objects.get(id=id)  
    student.delete()  
    return redirect("home-page")   

myCrudproject/crudprojectapp/templates/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
<meta charset="UTF-8">  
<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>

<title>{% block title %}{% endblock %}</title>
{% load static %}  

<link rel="stylesheet" href="../static/css/index.css">

<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />

</head> 
<body>
   <!-- Sidebar -->
<div class="sidebar">
   <div class="logo-details">
       <i class="bx bx-scan icon"></i>
       <div class="logo_name">HC.lts</div>
       <i class='bx bx-menu' id="btn" ></i>
   </div>
   <ul class="nav-list">
     <li>
       <a href="index.html">
         <i class='bx bx-grid-alt'></i>
         <span class="links_name">Dashboard</span>
       </a>
        <span class="tooltip">Dashboard</span>
     </li>
     <li>
      <a href="add.html">
       <i class='bx bx-user-plus' ></i>
       <span class="links_name">User</span>
      </a>
      <span class="tooltip">User</span>
    </li>
    <!-- <li>
     <a href="contact.html">
       <i class='bx bx-target-lock'></i>
               <span class="links_name">Tracking</span>
     </a>
     <span class="tooltip">Tracking</span>
   </li> -->
   
    <li>
      <a href="#">
        <i class='bx bx-folder' ></i>
        <span class="links_name">File Manager</span>
      </a>
      <span class="tooltip">Files</span>
    </li>
    
    <li>
      <a href="#">
        <i class='bx bx-heart' ></i>
        <span class="links_name">Saved</span>
      </a>
      <span class="tooltip">Saved</span>
    </li>
    <li>
      <a href="#">
        <i class='bx bx-cog' ></i>
        <span class="links_name">Setting</span>
      </a>
      <span class="tooltip">Setting</span>
    </li>
    <li class="profile">
        <div class="profile-details">
          <img src="../static/img/profile.jpg" alt="profile">
          <div class="name_job">
            <div class="name">Sarang Jupyo</div>
            <div class="job">Admin</div>
          </div>
        </div>
       <a href="{% url 'logout' %}"> <i class='bx bx-log-out' id="log_out" ></i></a>
    </li>
   </ul>
 </div>

 <!--MAIN CONTENT-->
 <section class="home-section"> 
   <div class="text">Dashboard</div>
   <div class="stable-wrap">
    <h3>List of Students</h3>
    {% block content %}{% endblock content %} 
  </div>
   

 </section>
   

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>

<script>
   $(document).ready( function () {
   $('#myTable').DataTable({ 
       info: false,
   });
   } );
</script>

<!-- sweet alert -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!-- <script>
Swal.fire(
  'Good job!',
  'You clicked the button!',
  'success'
)
</script> -->

<script src="../static/js/main.js"></script>
</body> 
</html>

myCrudproject/crudprojectapp/templates/edit.html
{% extends "base.html" %}
  
{% block title %}Edit Students Records{% endblock title %}
  
{% block content %}
<div class="form-wrap">
    <form method="POST" class="post-form" action="/update/{{student.id}}">  
    {% csrf_token %}  
    <div class="container">   
        <div class="col-12">  
            <h3>Update Details</h3>  
        </div> 
        <div class="form-label"> 
            <label>student ID:</label>  
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ student.id }}"/>    
        </div> 
        <div class="form-label"> 
            <label>First Name:</label>  
            <input type="text" class="form-control" name="fname" id="id_fname" required maxlength="100" value="{{ student.fname }}" />  
        </div> 
        <div class="form-label"> 
            <label>Last Name:</label>  
            <input type="text" class="form-control" name="lname" id="id_lname" required maxlength="100" value="{{ student.lname }}" />  
        </div> 
        <div class="form-label"> 
            <label>Gender:</label>  
            <div class="radio">
                <label class="radio-inline">
                    <input type="radio" name="gender" value="Female" {% if student.gender == "Female" %}checked{% endif %}>
                    Female
                </label>
                <label class="radio-inline">
                    <input type="radio" name="gender" value="Male" {% if student.gender == "Male" %}checked{% endif %}>
                    Male
                </label>
                <label class="radio-inline">
                    <input type="radio" name="gender" value="Other" {% if student.gender == "Other" %}checked{% endif %}>
                    Other
                </label>
            </div>
        </div> 

        <div class="form-label"> 
            <label>Address:</label>  
            <input type="text" class="form-control" name="address" id="address" required maxlength="100" value="{{ student.address }}" />  
        </div> 

        <div class="form-label"> 
            <label>Email:</label>  
            <input type="email" class="form-control" name="email" id="id_email" required maxlength="254" value="{{ student.email }}" />  
        </div> 
        <div class="form-label"> 
            <label>Contact:</label>  
            <input type="number" class="form-control" name="contact" id="id_contact" required maxlength="15" value="{{ student.contact }}" />  
        </div> 
        <div class="form-btn"> 
            <button type="submit" class="btn btn-success btn-lg">Update</button>  
        </div> 
    </div>  
    </form>  
{% endblock content %} 

myCrudproject/crudprojectapp/templates/index.html
{% extends "base.html" %}
  
{% block title %}Add New student Records{% endblock title %}
  
{% block content %}
<div class="form-wrap">
    <form method="POST" class="post-form" action="{% url 'addnew' %}">  
    {% csrf_token %}  
    <div class="container">  
        <div class="col-12">  
        <h3>Enter Details</h3>  
        </div>    
     
        <div class="form-label"> 
            <label>First Name:</label>  
            {{ form.fname }}   
        </div> 
        <div class="form-label"> 
            <label>Last Name:</label>  
            {{ form.lname }}   
        </div> 

        <div class="form-label"> 
            <label>Gender:</label> 
            <div class="radio">
                {% for radio in form.gender %}
                    <label class="radio-inline">
                        {{ radio }} 
                    </label>
                {% endfor %}
            </div>

        
        </div> 

        <div class="form-label"> 
            <label>Address:</label>  
            {{ form.address }}   
        </div> 

        <div class="form-label"> 
            <label>Email:</label>  
            {{ form.email }}   
        </div>  
        <div class="form-label"> 
            <label>Contact:</label>  
            {{ form.contact }}   
        </div>
        <div class="form-btn"> 
            <button type="submit" class="btn btn-primary">Submit</button>    
        </div> 
        
    </div>  
    </form>  

</div>
{% endblock content %} 

myCrudproject/crudprojectapp/templates/register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Login and Registration Form in HTML & CSS | CodingLab </title>
    {% load static %}  

    <link rel="stylesheet" href="../static/css/registerform.css">
    <!-- Fontawesome CDN Link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container">
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="../static/img/handle.jpg" alt="">
        <div class="text">
          <span class="text-1">Every new friend is a <br> new adventure</span>
          <span class="text-2">Let's get connected</span>
        </div>
      </div>
      <div class="back">
        <!--<img class="backImg" src="images/backImg.jpg" alt="">-->
        <div class="text">
          <span class="text-1">Complete miles of journey <br> with one step</span>
          <span class="text-2">Let's get started</span>
        </div>
      </div>
    </div>
    <!-- login form -->
    <div class="forms">
        <div class="form-content">
          <div class="login-form">
            <div class="title">Login</div>
          <form action="{% url 'login-page' %}" method="POST">
            {% csrf_token %}

            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="text" placeholder="Enter your username" name="uname" required>
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input type="password" placeholder="Enter your password" name="password"  required>
              </div>
              <div class="text"><a href="#">Forgot password?</a></div>
              <div class="button input-box">
                <input type="submit" value="Submit">
              </div>
              <div class="text sign-up-text">Don't have an account? <label for="flip">Sigup now</label></div>
            </div>
        </form>
      </div>

      <!-- Sign-up form -->
        <div class="signup-form">
          <div class="title">Signup</div>
        <form action="{% url 'register-page' %}" method="POST">
            {% csrf_token %}
            <div class="input-boxes">
                <div class="name-wrap">
                    <div class="input-box">
                        <input type="text" placeholder="First name" name="fname" required>
                    </div>
                    <div class="input-box">
                        <input type="text" placeholder="Last name" name="lname" required>
                    </div>
                </div>
                
                <div class="input-box">
                    <i class="fas fa-user"></i>
                    <input type="text" placeholder="Username" name="uname" required>
                  </div>

              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="text" placeholder="Enter your email" name="email" required>
              </div>

              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input type="password" placeholder="Enter your password" name="password" required>
              </div>
              <div class="button input-box">
                <input type="submit" value="Submit">
              </div>
              <div class="text sign-up-text">Already have an account? <label for="flip">Login now</label></div>
            </div>
      </form>
    </div>
    </div>
    </div>
  </div>
</body>
</html>

myCrudproject/crudprojectapp/templates/show.html
{% extends "base.html" %}
  
{% block title %}Student Records{% endblock title %}
  
{% block content %}
<div class="table-wrap">
        <div class="addbtn"><a href="/addnew">Add New Record</a></div>  
       
        <table id="myTable" class="display" >
        <thead>
            <!-- <th><input type="checkbox" id="checkall" /></th> -->
            <th>ID No.</th>
            <th>First Name</th>
            <th>last Name</th>
            <th>Gender</th>
            <th>Address</th>
            <th>Email</th>
            <th>Contact</th>
            <th>Action</th>
        </thead>
        <tbody>
        {% for students in student %}  
            <tr>  
            <!-- <td><input type="checkbox" class="checkthis" /></td> -->
            <td>{{ students.id }}</td>  
            <td>{{ students.fname }}</td>  
            <td>{{ students.lname }}</td>  
            <td>{{ students.gender }}</td>  
            <td>{{ students.address }}</td>  
            <td>{{ students.email }}</td>  
            <td>{{ students.contact }}</td>  
            <td> <a href="/edit/{{ students.id }}" class="btn btn-primary"><i class='bx bx-edit'></i></a>
            <a href="/delete/{{ students.id }}" class="btn btn-danger"><i class='bx bxs-trash'></i></a></td>  
            </tr>  
        {% endfor %} 
        </tbody>
        </table>
    </div>
{% endblock content %}